<?php

/**
 * @file
 * Slack Receive module.
 */

/**
 * Implements hook_menu().
 */
function slack_receive_menu() {
  $items = array();

  $items['admin/config/services/slack_receive'] = array(
    'title' => 'Slack Receive',
    'description' => 'Adjust Slack Receive settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slack_receive_configure_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/pages/slack_receive.admin.inc',
  );

  $items['slack_receive'] = array(
    'page callback' => 'slack_receive',
    'delivery callback' => 'slack_receive_deliver',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function slack_receive_help($path, $arg) {
  switch ($path) {
    case 'admin/help#slack_receive':
      $webhook_link = l(t("Outgoing Webhooks"),
        'https://api.slack.com/outgoing-webhooks');
      return '<p>' . t("Be sure to see the modules' README. Also, please save
        your Outgoing Webhook API token in the admin form below. This token
        authenticates requests from Slack to Drupal. Your teams' token should
        be accessible here: ") . $webhook_link . '</p>';
  }
}

/**
 * Hook definition and JSON output wrapper for receiving commands from Slack.
 *
 * See: https://api.slack.com/outgoing-webhooks.
 */
function slack_receive() {

  $data = &$_POST;

  // Check for a valid token.
  $token = variable_get('slack_receive_token', '');
  if (empty($data['token']) || $data['token'] !== $token) {
    return MENU_ACCESS_DENIED;
  }
  else {
    // Create custom hook so authenticated requests can
    // perform Drupal tasks.
    $response = module_invoke_all('slack_receive_api', $data);
    $data['text'] = array_shift($response);
  }

  return $data;
}

/**
 * JSON delivery callback method.
 *
 * Ensures responses always have correct headers set and Drupal doesn't
 * try to bootstrap an HTML error page.
 *
 * NOTE: Any non-200 statuses will not return a response inside Slack.
 */
function slack_receive_deliver($page_callback_result) {

  // If no result, return an error response.
  if (empty($page_callback_result['text'])) {
    $response['text'] = t("Sorry, that command was not found.");
  }
  else {

    // NOTE: Anything other than a 200 status code won't receive
    // a text response in your Slack channel. See README for details.
    switch ($page_callback_result) {
      case MENU_SITE_OFFLINE:
        drupal_add_http_header('Status', '503 Service unavailable');
        $response['text'] = t("Site is offline.");
        break;

      case MENU_ACCESS_DENIED:
        drupal_add_http_header('Status', '403 Forbidden');
        $response['text'] = t("Sorry, invalid API token.");
        break;

      default:
        $response = $page_callback_result;
    }
  }

  drupal_json_output($response);
  drupal_exit();
}
