<?php

/**
 * @file
 * Slack Receive Example module.
 */

/**
 * Implements hook_slack_receive_api().
 */
function slack_receive_example_slack_receive_api($data) {

  $args = explode(' ', $data);

  switch ($args[1]) {

    // Just like drush pm-list.
    case 'pm-list':
      $response = slack_receive_example_get_pm_list($args);
      break;

    // Cache clear.
    case 'cache-clear':
      $response = slack_receive_example_clear_cache($args);
      break;
  }

  return $response;
}

/**
 * Fetches contrib module status information.
 *
 * @param array $data
 *   The POST data from Slack.
 * @param array $args
 *   An array of the parsed command sent from Slack.
 *
 * @return array
 *   Slack Response.
 */
function slack_receive_example_get_pm_list(array $args) {

  // Note the use of escapeshellcmd() and escapeshellarg() to avoid
  // unwanted execution of shell commands from user input.
  $cmd = escapeshellcmd('drush pm-list');
  $cmd .= $args[2] ? ' | grep ' . escapeshellarg($args[2]) : '';
  exec($cmd, $results);

  // Slack Outgoing Webhooks integration requires
  // the 'text' response to be a single string.
  $list_string = '';
  foreach ($results as $result) {
    $list_string .= $result . "\n";
  }

  $response['text'] = $list_string;

  return $response;
}

/**
 * Clears drupal cache.
 *
 * @param array $args
 *   An array of the parsed command sent from Slack.
 *
 * @return array
 *   Slack Response.
 */
function slack_receive_example_clear_cache(array $args) {

  $cmd = escapeshellcmd('drush cache-clear');
  $cmd .= $args[2] ? ' ' . escapeshellarg($args[2]) : ' all';
  exec($cmd, $output, $status);

  // For some reason, drush cache-clear response text isn't returned
  // from exec(), but an exit status code is - 0 for success 1 for non-success.
  if ($status) {
    $response['text'] = "'$args[2]' " . t('is not a valid cache type.');
  }
  else {
    $cache_name = $args[2] ? $args[2] : 'all';
    $response['text'] = "'$cache_name' " . t('cache was cleared.');
  }

  return $response;
}
