<?php

/**
 * @file
 * Slack Receive module.
 */

/**
 * Implements hook_menu().
 */
function slack_receive_menu() {
  $items = array();

  $items['admin/config/services/slack_recieve'] = array(
    'title' => 'Slack Receive',
    'description' => 'Adjust Slack Receive settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('slack_receive_configure_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'path' => drupal_get_path('module', 'slack_receive') . '/includes/pages',
    'file' => 'slack_receive.admin.inc',
  );

  $items['slack_receive'] = array(
    'page callback' => 'slack_receive',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function slack_receive_help($path, $arg) {
  switch ($path) {
    case 'admin/help#slack_receive':
      $webhook_link = l(t("Outgoing Webhooks"),
        'https://api.slack.com/outgoing-webhooks');
      return '<p>' . t("Be sure to see the modules' README. Also, please save
        your Outgoing Webhook API token in the admin form below. This token
        authenticates requests from Slack to Drupal. Your teams' token should
        be accessible here: ") . $webhook_link . '</p>';

  }
}

/**
 * Hook definition and JSON output wrapper for receiving commands from Slack.
 *
 * See: https://api.slack.com/outgoing-webhooks.
 */
function slack_receive() {

  $data = $_POST;

  // Check for a valid token.
  $token = variable_get('slack_receive_token', '');
  if ($data['token'] !== $token) {
    $data = array('ERROR' => 'Invalid or missing token');
  }
  else {
    // Create custom hook so authenticated requests can
    // perform Drupal tasks.
    $data = module_invoke_all('slack_receive_api', $data);
  }

  drupal_json_output($data);
}
