<?php

/**
 * @file
 * Slack Receive Example module.
 */

/**
 * Implements hook_slack_receive_api().
 */
function slack_receive_example_slack_receive_api(array $data) {

  // Note that Slack unhelpfully names the initiating messages'
  // text string as 'text' and expects a response named 'text'
  // to print in the team chat.
  $args = explode(' ', $data['text']);

  switch ($args[1]) {

    // Just like drush pm-list.
    case 'pm-list':
      $response = slack_receive_example_get_pm_list($data, $args);
      break;

    // Cache clear.
    case 'cache-clear':
      $response = slack_receive_example_clear_cache($data, $args);
      break;
  }

  return $response;
}

/**
 * Fetches contrib module status information.
 *
 * @param array $data
 *   The POST data from Slack.
 * @param array $args
 *   An array of the parsed command sent from Slack.
 *
 * @return string
 *   Slack Response.
 */
function slack_receive_example_get_pm_list(array $data, array $args) {

  // Note the use of escapeshellcmd() and escapeshellarg() to avoid
  // unwanted execution of shell commands from user input.
  $cmd = escapeshellcmd('drush pm-list');
  $cmd .= $args[2] ? ' | grep ' . escapeshellarg($args[2]) : '';
  exec($cmd, $results);

  // Slack Outgoing Webhooks integration requires
  // the 'text' response to be a single string.
  $response = '';
  foreach ($results as $result) {
    $response .= $result . "\n";
  }

  // If Grep is empty, search string does not match any installed modules.
  if (empty($response)) {
    return t('No modules found.');
  }

  return $response;
}

/**
 * Clears drupal cache.
 *
 * @param array $data
 *   The POST data from Slack.
 * @param array $args
 *   An array of the parsed command sent from Slack.
 *
 * @return string
 *   Slack Response.
 */
function slack_receive_example_clear_cache(array $data, array $args) {

  $cmd = escapeshellcmd('drush cache-clear');
  $cmd .= $args[2] ? ' ' . escapeshellarg($args[2]) : ' all';
  $data['cmd'] = $cmd;
  exec($cmd, $output, $status);

  // For some reason, drush cache-clear response text isn't returned
  // from exec(), but an exit status code is - 0 for success 1 for non-success.
  if ($status) {
    $response = "'$args[2]' " . t('is not a valid cache type.');
  }
  else {
    $cache_name = $args[2] ? $args[2] : 'all';
    $response = "'$cache_name' " . t('cache was cleared.');
  }

  return $response;
}
